openapi: 3.0.3
info:
  title: Loyalty & Promo API for Online Cinema
  description: |
    Система лояльности для онлайн-кинотеатра: покупка платной версии, триал, скидки, генерация промокодов, применение,
    отслеживание отказов и откат, если оплата не прошла.
    - "POST /subscribe { user_id, subscription_id }"
    - Применяем или изменяем промокод после создания заказа.
    - "PATCH /subscribe {subscribe_order_id, user_id, promo_code }"
    - "Backend проверяет код и возвращает price_after_discount"
    - "Клиент платит price_after_discount"
    - "POST /subscribe/pay { user_id, subscribe_order_id }"
    - "POST /payments { user_id, amount, currency, "payment_method": "card" }"
    - "Если провал — POST /promo/revert { user_id, promo_id, subscribe_id }"
  version: "1.0.2"

servers:
  - url: https://api.yourcinema.example/v1
    description: Основной продакшн сервер
  - url: https://staging-api.yourcinema.example/v1
    description: Стейджинг для тестов

security:
  - api_key_auth: []

paths:
  /subscribe:
    get:
      summary: "Получить стоимость подписки с опциональным промокодом"
      parameters:
        - in: query
          name: promo
          schema:
            type: string
          description: |
            promo = trial → триал; иначе проверить код и вернуть `price_after_discount`.
      responses:
        '201':
          description: "Информация о созданной покупке"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscribe_cost_response'
        '400':
          description: "Неверный запрос или промокод недействителен"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /subscribe/checkout:
    get:
      summary: "Получить созданый пользователем заказ и его статус"
      responses:
        '200':
          description: "Информация о созданной покупке"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscribe_order_response'
        '400':
          description: "Неверный запрос или промокод недействителен"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
    post:
      summary: "Создать покупку (платная версия или триал) с опциональным промокодом"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subscribe_order_request'
      responses:
        '201':
          description: "Инфо о созданной покупке"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscribe_order_response'
        '400':
          description: "Неверный запрос или код недействителен"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

    patch:
      summary: "Добавить промокод к существующему заказу"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/apply_promo_request'
      responses:
        '200':
          description: "Обновлённый заказ"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscribe_order_response'
        '400':
          description: "Невалидный запрос или промокод недействителен"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '404':
          description: "Заказ не найден"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404_error_response'

  /subscribe/pay:
    post:
      summary: "Оплатить существующий заказ"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order_payment_request'
      responses:
        '200':
          description: "Заказ оплачен"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscribe_order_response'
        '400':
          description: "Неверный запрос или код недействителен"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '404':
          description: "Заказ не найден"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404_error_response'

components:
  schemas:
    error_response:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "Invalid request"

    404_error_response:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "Not found"

    subscribe_cost_response:
      type: object
      properties:
        subscription_id:
          type: string
        applied_promo_code:
          type: string
          nullable: true
        price_before_discount:
          type: number
          format: float
        price_after_discount:
          type: number
          format: float

    subscribe_order_request:
      type: object
      required:
        - subscription_id
      properties:
        subscription_id:
          type: string
        promo:
          type: string
          nullable: true
          description: |
            "trial" = триал, иначе промокод для расчёта `price_after_discount`

    subscribe_order_response:
      type: object
      properties:
        subscribe_order_id:
          type: string
        subscription_id:
          type: string
        applied_promo_code:
          type: string
          nullable: true
        price_before_discount:
          type: number
          format: float
        price_after_discount:
          type: number
          format: float
        status:
          type: string
          enum: [created, payment_pending, paid, payment_failed, cancelled]

    apply_promo_request:
      type: object
      required:
        - user_id
        - subscribe_order_id
        - subscription_id
      properties:
        user_id:
          type: string
          description: ID пользователя
        subscribe_order_id:
          type: string
          description: ID плана подписки
        subscription_id:
          type: string
        promo:
          type: string
          nullable: true
          description: |
            "trial" = триал, иначе промокод для расчёта `price_after_discount`

    order_payment_request:
      type: object
      required:
        - subscribe_order_id
      properties:
        subscribe_order_id:
          type: string
