openapi: 3.0.3
info:
  title: Loyalty & Promo API for Online Cinema
  description: |
    Система лояльности для онлайн-кинотеатра: покупка платной версии, триал, скидки, генерация промокодов, применение,
    отслеживание отказов и откат, если оплата не прошла.
    - "POST /subscribe { user_id, subscription_id }"
    - "PATCH /subscribe/{subscribe_order_id} { user_id, promo_code }"
    - "Backend проверяет код и возвращает price_after_discount"
    - "Клиент платит price_after_discount"
    - "Если провал — POST /promo/revert { user_id, promo_id, subscribe_id }"
    - "Админ: GET /promo, GET /promo/{promo_id}, GET /promo/failures/{promo_id}"
  version: "1.0.2"

servers:
  - url: https://api.yourcinema.example/v1
    description: Основной продакшн сервер
  - url: https://staging-api.yourcinema.example/v1
    description: Стейджинг для тестов

security:
  - api_key_auth: []

components:
  schemas:
    error_response:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "Invalid promo code"

    404_error_response:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "Not found"

    subscribe_request:
      type: object
      required:
        - user_id
        - subscription_id
      properties:
        user_id:
          type: string
          description: ID пользователя в системе
        subscription_id:
          type: string
          description: ID подписки в системе

    subscribe_order_response:
      type: object
      properties:
        subscribe_id:
          type: string
          description: Уникальный ID покупки
        applied_promo_code:
          type: string
          nullable: true
          description: Если промокод успешно применён, тут его код
        price_before_discount:
          type: number
          format: float
          description: Исходная сумма к оплате до учета скидки
        price_after_discount:
          type: number
          format: float
          description: Итоговая сумма к оплате после учёта скидки
        status:
          type: string
          enum: [created, payment_pending, paid, payment_failed, cancelled]
          description: Статус оплаты

    apply_promo_request:
      type: object
      required:
        - user_id
        - prome_code
      properties:
        user_id:
          type: string
        prome_code:
          type: string


paths:
  /subscribe:
    post:
      summary: "Создать покупку (платная версия или триал) с опциональным промокодом"
      parameters:
        - in: query
          name: promo
          schema:
            type: string
          description: |
            promo = trial → триал; иначе проверить код и вернуть `price_after_discount`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subscribe_request'
      responses:
        '201':
          description: "Информация о созданной покупке"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscribe_order_response'
        '400':
          description: "Неверный запрос или промокод недействителен"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /subscribe/{subscribe_order_id}:
    patch:
      summary: "Добавить промокод к существующей покупке подписки"
      parameters:
        - in: path
          name: subscribe_order_id
          schema:
            type: string
          description: Уникальный ID заказа подписки
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/apply_promo_request'
      responses:
        '200':
          description: "Обновлённый заказ подписки"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscribe_order_response'
        '400':
          description: "Невалидный запрос или промокод недействителен"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '404':
          description: "Заказ подписки не найден"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404_error_response'
